"""Initial migration

Revision ID: 3e3a6e0ef96b
Revises: 
Create Date: 2025-09-30 01:33:43.967972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e3a6e0ef96b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('puzzles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('puzzle_type', sa.String(length=20), nullable=False),
    sa.Column('target_symbol', sa.String(length=20), nullable=False),
    sa.Column('event_data', sa.JSON(), nullable=False),
    sa.Column('hidden_truth', sa.Text(), nullable=False),
    sa.Column('correct_hypothesis', sa.Text(), nullable=False),
    sa.Column('available_clues', sa.JSON(), nullable=False),
    sa.Column('base_reward_xp', sa.Integer(), nullable=False),
    sa.Column('time_bonus_multiplier', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_puzzles'))
    )
    op.create_index('ix_puzzles_difficulty', 'puzzles', ['difficulty'], unique=False)
    op.create_index('ix_puzzles_symbol', 'puzzles', ['target_symbol'], unique=False)
    op.create_index('ix_puzzles_type', 'puzzles', ['puzzle_type'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('experience', sa.Integer(), nullable=False),
    sa.Column('current_class', sa.String(length=50), nullable=False),
    sa.Column('energy', sa.Integer(), nullable=False),
    sa.Column('max_energy', sa.Integer(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('preferred_mentor', sa.String(length=50), nullable=False),
    sa.Column('unlocked_skills', sa.JSON(), nullable=False),
    sa.Column('unlocked_features', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_active', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.create_table('mentor_interactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('mentor_id', sa.String(length=50), nullable=False),
    sa.Column('context', sa.String(length=50), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('response', sa.Text(), nullable=False),
    sa.Column('current_situation', sa.JSON(), nullable=True),
    sa.Column('helpfulness_rating', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_mentor_interactions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mentor_interactions'))
    )
    op.create_index('ix_mentor_interactions_created', 'mentor_interactions', ['created_at'], unique=False)
    op.create_index('ix_mentor_interactions_mentor', 'mentor_interactions', ['mentor_id'], unique=False)
    op.create_index('ix_mentor_interactions_user', 'mentor_interactions', ['user_id'], unique=False)
    op.create_table('portfolios',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('initial_cash', sa.Float(), nullable=False),
    sa.Column('current_cash', sa.Float(), nullable=False),
    sa.Column('total_value', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_portfolios_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_portfolios'))
    )
    op.create_table('puzzle_progress',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('puzzle_id', sa.String(length=36), nullable=False),
    sa.Column('investigation_count', sa.Integer(), nullable=False),
    sa.Column('discovered_clues', sa.JSON(), nullable=False),
    sa.Column('clue_discovery_times', sa.JSON(), nullable=False),
    sa.Column('hypothesis_submitted', sa.Boolean(), nullable=False),
    sa.Column('hypothesis_text', sa.Text(), nullable=True),
    sa.Column('confidence_level', sa.Float(), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('is_solved', sa.Boolean(), nullable=False),
    sa.Column('accuracy_score', sa.Float(), nullable=True),
    sa.Column('xp_earned', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['puzzle_id'], ['puzzles.id'], name=op.f('fk_puzzle_progress_puzzle_id_puzzles')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_puzzle_progress_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_puzzle_progress')),
    sa.UniqueConstraint('user_id', 'puzzle_id', name='uq_puzzle_progress_user_puzzle')
    )
    op.create_index('ix_puzzle_progress_user', 'puzzle_progress', ['user_id'], unique=False)
    op.create_table('tutorial_progress',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('current_stage', sa.String(length=50), nullable=False),
    sa.Column('completed_stages', sa.JSON(), nullable=False),
    sa.Column('completion_rate', sa.Float(), nullable=False),
    sa.Column('stage_data', sa.JSON(), nullable=False),
    sa.Column('puzzle_tutorial_progress', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('last_activity', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_tutorial_progress_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tutorial_progress')),
    sa.UniqueConstraint('user_id', name=op.f('uq_tutorial_progress_user_id'))
    )
    op.create_table('orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('portfolio_id', sa.String(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('order_type', sa.String(length=20), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('filled_quantity', sa.Integer(), nullable=False),
    sa.Column('execution_price', sa.Float(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], name=op.f('fk_orders_portfolio_id_portfolios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders'))
    )
    op.create_index('ix_orders_created_at', 'orders', ['created_at'], unique=False)
    op.create_index('ix_orders_symbol', 'orders', ['symbol'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('portfolio_id', sa.String(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('average_price', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], name=op.f('fk_positions_portfolio_id_portfolios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_positions')),
    sa.UniqueConstraint('portfolio_id', 'symbol', name='uq_position_portfolio_symbol')
    )
    op.create_index('ix_positions_symbol', 'positions', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_positions_symbol', table_name='positions')
    op.drop_table('positions')
    op.drop_index('ix_orders_symbol', table_name='orders')
    op.drop_index('ix_orders_created_at', table_name='orders')
    op.drop_table('orders')
    op.drop_table('tutorial_progress')
    op.drop_index('ix_puzzle_progress_user', table_name='puzzle_progress')
    op.drop_table('puzzle_progress')
    op.drop_table('portfolios')
    op.drop_index('ix_mentor_interactions_user', table_name='mentor_interactions')
    op.drop_index('ix_mentor_interactions_mentor', table_name='mentor_interactions')
    op.drop_index('ix_mentor_interactions_created', table_name='mentor_interactions')
    op.drop_table('mentor_interactions')
    op.drop_index('ix_users_username', table_name='users')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_puzzles_type', table_name='puzzles')
    op.drop_index('ix_puzzles_symbol', table_name='puzzles')
    op.drop_index('ix_puzzles_difficulty', table_name='puzzles')
    op.drop_table('puzzles')
    # ### end Alembic commands ###
